# Generated by Django 2.2.1 on 2019-05-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_comment_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='图片')),
                ('desc', models.CharField(max_length=30, verbose_name='描述')),
            ],
            options={
                'verbose_name': '相册集',
                'verbose_name_plural': '相册集',
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '图片集', 'verbose_name_plural': '图片集'},
        ),
    ]
